module.exports = {
    // repositories: [
    //     "stackabletech/documentation",
    //     "stackabletech/hdfs-operator",
    //     "stackabletech/docker-images",
    //     "stackabletech/kafka-operator",
    //     "stackabletech/nifi-operator",
    //     "stackabletech/druid-operator",
    //     "stackabletech/commons-operator",
    //     "stackabletech/operator-rs",
    //     "stackabletech/opa-operator",
    //     "stackabletech/stackablectl",
    //     "stackabletech/operator-templating",
    //     "stackabletech/airflow-operator",
    //     "stackabletech/trino-operator",
    //     "stackabletech/hive-operator",
    //     "stackabletech/stackable-utils",
    //     "stackabletech/hbase-normalizer",
    //     "stackabletech/zookeeper-operator",
    //     "stackabletech/superset-operator",
    //     "stackabletech/spark-k8s-operator",
    //     "stackabletech/secret-operator",
    //     "stackabletech/listener-operator",
    //     "stackabletech/hbase-operator",
    //     "stackabletech/beku.py",
    //     "stackabletech/documentation-ui",
    // ],
    repositories: [  'stackabletech/operator-templating'
    ],
    gitAuthor: "\"Stacky McStackface\" <serviceaccounts@stackable.de>",
    includeForks: true,
    logFileLevel: 'debug',
    logLevel: 'debug',
    recreateClosed: 'true',
    force: {
      schedule: [],
      prCreation: "immediate",
    }
  };