module.exports = {
    repositories: [
        "stackabletech/airflow-operator",
        "stackabletech/beku.py",
        "stackabletech/commons-operator",
        "stackabletech/crdsdocs-generator",
        "stackabletech/docker-images",
        "stackabletech/documentation",
        "stackabletech/documentation-ui",
        "stackabletech/druid-opa-authorizer",
        "stackabletech/druid-operator",
        "stackabletech/edc-operator",
        "stackabletech/hbase-normalizer",
        "stackabletech/hbase-operator",
        "stackabletech/hdfs-opa-authorizer",
        "stackabletech/hdfs-operator",
        "stackabletech/hdfs-rack-identifier",
        "stackabletech/hdfs-topology-provider",
        "stackabletech/hello-world-operator",
        "stackabletech/hello-world-operator",
        "stackabletech/hive-operator",
        "stackabletech/image-tools",
        "stackabletech/kafka-operator",
        "stackabletech/listener-operator",
        "stackabletech/nifi-opa-authorizer",
        "stackabletech/nifi-operator",
        "stackabletech/nifi-webhook-authorizer",
        "stackabletech/opa-operator",
        "stackabletech/operator-rs",
        "stackabletech/operator-templating",
        "stackabletech/product-config",
        "stackabletech/secret-operator",
        "stackabletech/spark-k8s-operator",
        "stackabletech/stackable-cockpit",
        "stackabletech/stackable-utils",
        "stackabletech/stackablectl",
        "stackabletech/superset-operator",
        "stackabletech/tokio-zookeeper",
        "stackabletech/trino-operator",
        "stackabletech/zookeeper-operator"
    ],
    gitAuthor: "\"Stacky McStackface\" <serviceaccounts@stackable.de>",
    forkProcessing: 'enabled',
    logFileLevel: 'debug',
    logLevel: 'debug',
    force: {
      schedule: [],
      prCreation: "immediate",
    }
  };
