---
- hosts: all
  tasks:
    - name: install curl
      yum: 
        name: curl
        state: present
    - name: copy test script to server
      template:
        src: test.sh.j2
        dest: /tmp/test.sh
        mode: 0700
    - name: execute test script
      shell: |
        /tmp/test.sh
    - name: fetch results
      fetch:
        src: /tmp/{{ inventory_hostname }}.log
        dest: results/
        flat: yes