name: Build Matterbridge

on:
  workflow_dispatch:

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      -
        name: Login to Stackable Harbor
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0 
        with:
          registry: oci.stackable.tech
          username: robot$stackable+github-action-build
          password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
      -
        name: Set up Cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # tag=v3.3.0
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ./tools/matterbridge
          file: ./tools/matterbridge/Dockerfile
          push: true
          tags: oci.stackable.tech/stackable/matterbridge:0.0.0-dev
          build-args: |
            REVISION=${{ github.sha }}
            VERSION=dev
      -
        name: Sign the published image
        run: cosign sign -y oci.stackable.tech/stackable/matterbridge@${{ steps.build-and-push.outputs.digest }}
