name: Publish CI Preprocessor as Docker image

on:
  workflow_dispatch:

jobs:

  ci-preprocessor:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: docker.stackable.tech
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}

      - uses: docker/build-push-action@v2.4.0
        with:
          context: tools/ci-preprocessor/
          tags: docker.stackable.tech/ci-preprocessor:latest
          push: true
