---
name: Run Renovate against all Repositories

on:
  workflow_dispatch:

inputs:
    dry-run:
      type: boolean
      description: Perform a dry run and just log changes, but don't open any pull requests

env:
  # Look at https://hub.docker.com/r/renovate/renovate/tags and identify new versions if an
  # update is required
  RENOVATE_VERSION: sha256:3e59ae8e4251678f7a0ef5c0abc4e0abf643b5b10bcbbb36fc51c4427533f4d4

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        run: docker run --rm --volume "renovate/config.js:/usr/src/app/config.js" --env RENOVATE_TOKEN="${{ secrets.STACKY_MC_STACKFACE_TOKEN }}" --env LOG_LEVEL=debug --env RENOVATE_DRY_RUN=full renovate/renovate@$RENOVATE_VERSION
